INCLUDES = -I/home/dzm/opencv3_4/include
LIBS = -lopencv_core -lopencv_imgproc -lopencv_highgui
LIBDIRS = -L/home/dzm/opencv3_4/lib64

main.o : main.cpp
	g++ -o main.o main.cpp $(INCLUDES) $(LIBDIRS) $(LIBS)
